version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: user123
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: monthlyExpensesDb
    ports:
      - "3316:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
